import './js/languageTranslate';
import './js/menu';
import './js/faq';
import './js/activities';
import './js/map';
import './js/more';
import './js/topBtn';
import './js/switchLangBtn';
import './js/modal';
